---
- name: Rollback Proxmox snapshots after converge
  hosts: localhost
  gather_facts: false
  vars:
    snapshot_name: "molecule-before"
    proxmox_api: &proxmox_api
      api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
      api_port: "{{ lookup('env', 'PROXMOX_PORT') | int }}"
      api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
      api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
      api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
      validate_certs: false

  tasks:
    - name: Rollback to snapshot
      community.proxmox.proxmox_snap:
        <<: *proxmox_api
        vmid: "{{ item }}"
        snapname: "{{ snapshot_name }}"
        state: rollback
        timeout: 120
      loop: [153, 167]

    - name: Delete snapshot
      community.proxmox.proxmox_snap:
        <<: *proxmox_api
        vmid: "{{ item }}"
        snapname: "{{ snapshot_name }}"
        state: absent
      loop: [153, 167]
