# Download 3-rd party software to `pld_bin_path` setting +x
- name: "Download_regular_files: {{ item.destination }}"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ pld_bin_path }}/{{ item.destination }}"
    mode: "0755"
    force: true
  changed_when: false
  retries: "{{ pld_retries_count }}"
  delay: "{{ pld_delay_time }}"
  register: r_download_files
  until: r_download_files is success
  tags:
    - base
    - downloads
    - apps
- name: Put_desktop_files_for_applications
  ansible.builtin.copy:
    dest: /usr/share/applications
    src: "{{ item.desktop_file }}"
    owner: root
    group: root
    mode: "0644"
  when: item.desktop_file is defined and item.desktop_file | length > 0
  any_errors_fatal: false
  become: true
  become_user: root
  register: r_put_desktop_files
  retries: "{{ pld_retries_count }}"
  delay: "{{ pld_delay_time }}"
  until: r_put_desktop_files is success
  tags:
    - base
    - downloads
    - apps
- name: Refresh_desktop_database
  ansible.builtin.shell: update-desktop-database
  register: r_refresh_desktop_database
  until: r_refresh_desktop_database is success
  retries: "{{ pld_retries_count }}"
  delay: "{{ pld_delay_time }}"
  failed_when: r_refresh_desktop_database.rc != 0
  ignore_errors: true
  changed_when: false
  tags:
    - base
    - downloads
    - apps
